# Generated by Django 4.1 on 2022-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nacimiento', models.DateTimeField()),
                ('parentesco', models.CharField(max_length=15)),
            ],
        ),
    ]
